#!/usr/bin/env python

import sys

from topic_op_ros.topic_op_ros import TopicOp
from rqt_gui.main import Main

plugin = 'topic_op_ros'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))

